export const MUSIC_ADDED = "MUSIC_ADDED";
export const MUSIC_UPDATED = "MUSIC_UPDATED";
export const MUSIC_REMOVED = "MUSIC_DELETED";
export const MUSICS_ADDED = "MUSICS_ADDED";
export const MUSICS_UPDATED = "MUSICS_UPDATED";
export const MUSICS_REMOVED = "MUSICS_REMOVED";
