name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache node_modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install and Build
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Prepare package
        run: |
          yarn

      - name: Generate codes for GraphQL
        run: |
          yarn codegen

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
